apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/backend/data
              name: open-webui-storage
            - mountPath: /root/.ollama
              name: ollama-storage
          args:
            - '--models-path=/root/.ollama/models'
      volumes:
        - name: open-webui-storage
          persistentVolumeClaim:
            claimName: open-webui-pvc
        - name: ollama-storage
          persistentVolumeClaim:
            claimName: ollama-pvc
