apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: ollama
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
          env:
            - name: OLLAMA_API_BASE_URL
              value: 'http://ollama-service:11434/api/chat' # Updated to use service name
            - name: OLLAMA_ORIGINS
              value: '*'
            - name: WEBUI_AUTH_ENABLED
              value: 'false'
            - name: WEBUI_AUTH_PROVIDER
              value: 'none'
            - name: ENABLE_SIGNUP
              value: 'true'
            - name: WEBUI_SECRET_KEY
              value: 'mysecretkey'
